# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.10.2
maven_group=zabi.minecraft.extraalchemy
archives_base_name=extraalchemy-fabric

# Dependencies
fabric_api_version=0.92.8+1.20.1
fabric_kotlin_version=1.13.11+kotlin.2.3.21

modmenu_version=7.2.2
clothconfig_version=11.1.136
rei_version=12.1.785
pehkui_version=3.8.3
trinkets_version=3.7.2
patchouli_version=1.20.1-85-FABRIC
inventorio_version=6439098
cca_version=5.2.3